replicaCount: 1

image:
  repository: hello-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  - name: APP_VERSION
    value: "1.0.0"
  - name: PORT
    value: "8080" 